### ISSUE TITLE
request help:  dashboards are not refreshed after the update is successful

### ISSUE THREAD

**Issue by valleyFrost** [apache/apisix-dashboard#2285] opened 2022-01-18 01:53 UTC
### Issue description

The dashboard version is apisix-dashboard-2.10.1-0.el7.x86_64. RPM.
To upgrade from 2.9 to 2.10, perform the following steps
```
cd /usr/local/apisix/
rm -rf dashboard
RPM -ivh apisix-dashboard-2.10.1-0.el7.x86_64. RPM --nodeps --force
```
Some dashboards are not refreshed after the update is successful and take effect after being restarted. However, the refresh failure occurs again after a period of time, and the dashboard takes effect after being restarted.

### Environment

- apisix version (cmd: `apisix version`):apisix-2.10.0-0.el7.x86_64.rpm
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty-1.19.9.1-1.el7.x86_64.rpm
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):etcd-v3.5.1-linux-amd64
- apisix-dashboard version, if have:apisix-2.10.0-0.el7.x86_64.rpm
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment] 2022-01-18 02:04
> Some dashboards are not refreshed 

Hi @valleyFrost, may I know what's "are not refreshed"? You mean the Dashboard UI is the same as previous version? If it's, please open you Browser and clear cache, or use `Shift + Command + R` to force refresh, I'm not sure if you encounter Cache issue.

**Comment by valleyFrost** [comment] 2022-01-18 02:22
不好意思，没描述清除。不是页面缓存，清除试过了。当我通过dashboard进行页面操作以后，页面显示操作成功，例如新增路由或上游服务。我能正常使用新增的路由或上游服务，apisix上配置接口可以调通。但是有的时候dashboard再更新升级后刷新不出来新增的路由或上游服务，只显示以前的数据，其实新增的路由可以配置接口使用并收到成功响应&nbsp;。

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] request help:  dashboards are not refreshed after the update is successful (Issue #2285)





  
Some dashboards are not refreshed
  
Hi @valleyFrost, may I know what's "are not refreshed"? You mean the Dashboard UI is the same as previous version? If it's, please open you Browser and clear cache, or use Shift + Command + R to force refresh, I'm not sure if you encounter Cache issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by juzhiyuan** [comment] 2022-01-18 03:23
🤔 cc @nic-chen to have a look, thanks!

**Comment by nic-chen** [comment] 2022-01-18 07:37
hi @valleyFrost
Hot update is currently not supported, and a restart is required after the update.

**Comment by Buttires1984** [comment] 2022-01-20 13:25
So can we close this issue or shall we implement the upload feature？

**Comment by juzhiyuan** [comment] 2022-01-21 01:15
I will label it as `doc` and close this :)

**Comment by nic-chen** [comment] 2022-01-27 03:09
Consider whether the intermediate watch etcd failed.

Please upload the error log at your convenience. @valleyFrost

**Comment by xianshun163** [comment] 2022-02-08 07:39
I have reproduce this issue  like  this :
1、the  etcd  have 3 node
2、shutdown  the  leader node  of  the  etcd.
3、go to  the dashboard, and  make some change. then  the  change is ok,  and it is change in the etcd. 
     But, the dashboard  is  still the  old value, can not get the  new  value。 
     It  looks like  the  dashboard use the  local  cache。

**Comment by bzp2010** [comment] 2022-02-08 07:45
> I have reproduce this issue like this : 1、the etcd have 3 node 2、shutdown the leader node of the etcd. 3、go to the dashboard, and make some change. then the change is ok, and it is change in the etcd. But, the dashboard is still the old value, can not get the new value。 It looks like the dashboard use the local cache。

I will try to reproduce it again and find a solution.

**Comment by bzp2010** [comment] 2022-02-08 14:38
### Update

I tried single-node and multi-node etcd, for node/leader, and found nothing that could cause `Watch` to fail. If the etcd is unavailable, writes to the etcd will be cached and redone when the connection is restored (this is incorrent and may result in duplicate writes, but has nothing to do with the cache not being updated) 

Whether it is a single-node or multi-node etcd service, the client can restore the connection itself.

![image](https://user-images.githubusercontent.com/8078418/153009100-6e219df1-71da-4a87-a510-b26c11bc57ef.png)

**Comment by juzhiyuan** [comment] 2022-02-13 10:57
ping @valleyFrost @xianshun163 as a volunteer from community, my WeChat is JuShaoyao and you could add me and let's a meet to reproduce this :)

**Comment by valleyFrost** [comment] 2022-02-14 01:57
The problem I have encountered should be the situation reappearing on @xianshun163. My ETCD cluster used to have old nodes suspended and restarted. After controlling the ETCD cluster with no fewer nodes, there is no dashboard display problem, and the error log cannot be taken out before the live network. You can close this issue, thanks for your help.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix-dashboard"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 晚上6:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix-dashboard] request help:  dashboards are not refreshed after the update is successful (Issue #2285)





 
ping @valleyFrost @xianshun163 as a volunteer from community, my WeChat is JuShaoyao and you could add me and let's a meet to reproduce this :)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Closed** 2022-02-15 01:12 UTC
Labels: enhancement, doc
