### ISSUE TITLE
Duplicate def upstream on api doc

### ISSUE THREAD

**Issue by batman-ezio** [apache/apisix-dashboard#1662] opened 2021-03-24 03:05 UTC
## Issue description
![image](https://user-images.githubusercontent.com/80014017/112247957-19258280-8c90-11eb-9015-0aafedbe6b70.png)
there are two Upstream `Upstream` and `UpstreamDef ` in the document https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/api/api.md, 
and there are some fields missing compare to the admin api https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#upstream

for example. scheme field is define in the type UpstreamDef struct , but not display in the md file

are we still use go-swagger to generate md files?
https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/FAQ.md#5-how-to-write-api-documentation

## Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* Browser version, if have:

**Comment by nic-chen** [comment] 2021-03-26 10:07
oh, it's not a bug.

UpsteamDef is a public structure, route, upstream and service all refer to it.

**Comment by Engine-AI** [comment] 2021-04-12 12:59
@nic-chen @juzhiyuan  hi, If it is not a bug, please close this Issue.

**Comment by nic-chen** [comment] 2021-04-12 14:57
I think we could close this issue now. If you have any problem, just reopen it.

**Closed by nic-chen** 2021-04-12 14:57 UTC
Labels: bug
