### ISSUE TITLE
feat: Show route ID at LIST and EDIT views in dashboard

### ISSUE THREAD

**Issue by batman-ezio** [apache/apisix-dashboard#1595] opened 2021-03-15 09:25 UTC
# Feature request

## Please describe your feature

follow this guide to  https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started.md
to create a test route , the final route  is 
```
{
  "action": "get",
  "node": {
    "value": {
      "plugins": {
        "proxy-rewrite": {
          "scheme": "https",
          "regex_uri": ["^\/samplePrefix\/get(.*)", "\/get$1"]
        },
        "key-auth": {}
      },
      "id": "5",
      "uri": "\/samplePrefix\/get",
      "update_time": 1615794114,
      "status": 1,
      "upstream_id": 50,
      "priority": 0,
      "create_time": 1615793637
    },
    "key": "\/apisix\/routes\/5"
  },
  "count": "1"
}

```
The id field is `id` which is 5 here, 
but when I open `dashboard`,  it use `name` as a required and primary key.  and there's no place to display `id` in the UI.
User can not  even go to the next step in the edit mode to see all the data
![image](https://user-images.githubusercontent.com/80014017/111131167-ee15a180-85b2-11eb-88bf-322b44fbaf52.png)
![image](https://user-images.githubusercontent.com/80014017/111131336-20bf9a00-85b3-11eb-806f-d415898a8f0f.png)

## add default name 
-  change logic in the PUT route api, set a default name from the url params if there's no name pass in the body
 - display id field in List.And Edit route view

**Comment by nic-chen** [comment] 2021-03-15 10:09
@batman-ezio  Unique identifier of a route is ID.

**Comment by batman-ezio** [comment] 2021-03-16 06:10
how about display the id field in route and upstream list view ?  @nic-chen

**Comment by imjoey** [comment] 2021-03-16 07:04
@batman-ezio thanks for reporting and it's a bug actually.

IMHO this bug is caused by the route name is considered as a mandatory field when creating a route from Dashboard, while it's optional via APISIX Admin API. @nic-chen @liuxiran Any insights on this?

**Comment by nic-chen** [comment] 2021-03-16 07:31
> @batman-ezio thanks for reporting and it's a bug actually.
> 
> IMHO this bug is caused by the route name is considered as a mandatory field when creating a route from Dashboard, while it's optional via APISIX Admin API.
> 
> How about allow the same route name and show the ID in WebUI, which is the unique key ?
> 
> @nic-chen @liuxiran Any insights on this?

I think name of resource should be  a mandatory field, there is no reason to use the same name for different routes or services.

**Comment by liuxiran** [comment] 2021-03-16 07:53
Fe focuses on the user experience, `name` is better to distinguish a route, so we set `name` as a required key.
while API focuses on the feature, `name` is not the key field, so it is not reqired in admin-api, that is also reasonable IMHO
so, how about just keep the current UE in dashboard, when user create a route without a name by admin-api, they have to set the `name` in dashboard page.

**Comment by imjoey** [comment] 2021-03-16 08:01
> Fe focuses on the user experience, `name` is better to distinguish a route, so we set `name` as a required key.
> while API focuses on the feature, `name` is not the key field, so it is not reqired in admin-api, that is also reasonable IMHO
> so, how about just keep the current UE in dashboard, when user create a route without a name by admin-api, they have to set the `name` in dashboard page.

@nic-chen @liuxiran  agreed +1 for keeping this still.

@batman-ezio What do you think? Looking forward to your feedback. Thanks.

**Comment by batman-ezio** [comment] 2021-03-17 07:49
@imjoey agree 
but for the better FE, can we add id file and display in the LIST view?
when user can route by admin api  Put `/route/a1` and `route/a2` and so on. 
they can easily find their routes by looking up the id field

@nic-chen @liuxiran

**Comment by nic-chen** [comment] 2021-03-17 10:09
> @imjoey agree
> but for the better FE, can we add id file and display in the LIST view?
> when user can route by admin api Put `/route/a1` and `route/a2` and so on.
> they can easily find their routes by looking up the id field
> 
> @nic-chen @liuxiran

I think it's OK for us.

**Comment by liuxiran** [comment] 2021-03-17 21:47
> @imjoey agree
> but for the better FE, can we add id file and display in the LIST view?
> when user can route by admin api Put `/route/a1` and `route/a2` and so on.
> they can easily find their routes by looking up the id field
> 
> @nic-chen @liuxiran

Agree with you to display the `id` field in the list view which is already returned by `/apisix/admin/routes` in manager-api

**Comment by imjoey** [comment] 2021-03-18 08:02
> @imjoey agree
> but for the better FE, can we add id file and display in the LIST view?
> when user can route by admin api Put `/route/a1` and `route/a2` and so on.
> they can easily find their routes by looking up the id field
> 
> @nic-chen @liuxiran

@batman-ezio agreed +1 for show route ID on LIST and EDIT pages.

**Comment by mangoGoForward** [comment] 2021-12-03 15:17
I'd like to work on this issue, pls assign to me.
/assign

**Comment by juzhiyuan** [comment] 2021-12-08 03:16
Hi @mangoGoForward, you could do it if no PR linked to this issue 😄 If I'm late to reply you, just @ me.

**Comment by juzhiyuan** [comment] 2021-12-08 03:17
Oh btw, we have a meeting today, welcome to join in if you have time 😄 see https://github.com/apache/apisix/discussions/5721

**Comment by mangoGoForward** [comment] 2021-12-29 02:37
> Oh btw, we have a meeting today, welcome to join in if you have time 😄 see [apache/apisix#5721](https://github.com/apache/apisix/discussions/5721)

So regretful missing the meeting, I was delayed by other things.

**Comment by juzhiyuan** [comment] 2021-12-29 04:10
> > Oh btw, we have a meeting today, welcome to join in if you have time 😄 see [apache/apisix#5721](https://github.com/apache/apisix/discussions/5721)
> 
> So regretful missing the meeting, I was delayed by other things.

Oh it doesn't matter, today we have the meeting at 20:00 PM, see https://docs.qq.com/doc/DTkd3a2RraXBCaklm (Chinese Version)

**Closed** 2022-01-08 02:08 UTC
Labels: good first issue
