### ISSUE TITLE
feat: Improve testing coverage for the POST and PATCH methods of the resources

### ISSUE THREAD

**Issue by imjoey** [apache/apisix-dashboard#1332] opened 2021-01-19 06:02 UTC
# Feature request

## Please describe your feature

At present, most test cases in Backend E2E and Unit-test cases are using `PUT` method for creating and updating the resource, which leads to extremely low testing coverage for creating by `POST` and updating by `PATCH`.

## Describe the solution you'd like

So it would be much better that if we could add more test cases for the `POST` and `PATCH` methods of the resource. Of course, I would say adding missing test cases is heavy work, so let us fix this gradually.

**Comment by starsz** [comment] 2021-01-20 11:12
Aha! Much appreciated.

**Comment by Jaycean** [comment] 2021-01-29 03:23
I hope to help add more test cases.

**Comment by juzhiyuan** [comment] 2021-01-29 03:30
@Jaycean Assign to you! Thanks a lot!

**Comment by imjoey** [comment] 2021-01-29 03:35
> I hope to help add more test cases.

@Jaycean thanks a lot. 😄

**Comment by Jaycean** [comment] 2021-02-05 04:48
issue: #1161
Planned unit test refactoring of ssl,route,upstream,service.
Unit testing of the patch method will be added.

**Comment by nic-chen** [comment] 2021-03-15 13:20
@Jaycean  could we close this issue now ?

**Comment by Jaycean** [comment] 2021-03-15 13:25
> @Jaycean could we close this issue now ?

The issue is closed and the test case is complete. If there is any problem, open it again.

**Closed by Jaycean** 2021-03-15 13:25 UTC
Labels: backend, testcase
