### ISSUE TITLE
[Bug]: When creating a route, the search service input box cannot be customized.

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix-dashboard#2649] opened 2022-10-21 01:55 UTC
### Issue description

When creating a route, the search service input box cannot be customized.
![image](https://user-images.githubusercontent.com/72343596/197092552-6210eaec-b403-4dbe-9955-af72f743d0c0.png)

### Expected behavior

Supports entering the name of the service you want to select

### How to Reproduce

1. Visit create route page
2. Click the service input
3. Type any character
4. You can see the error

### Screenshots

![image](https://user-images.githubusercontent.com/72343596/197092824-5630892a-3571-43da-ada1-def9decf755c.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by wangchuaichuai** [comment] 2022-10-21 05:19
1

**Comment by SkyeYoung** [comment] 2022-10-21 06:25
@wangchuaichuai What are you saying?

**Comment by hf400159** [comment] 2022-10-31 10:13
In this text box, when you enter any content of the word (eg: `a`), the page will become blank, as shown above.
![image](https://user-images.githubusercontent.com/97138894/198984673-f78b009e-4fb6-4af8-bbac-8634b95f8245.png)

![screenshots](https://user-images.githubusercontent.com/97138894/198984186-bb90d90f-7560-4535-8bc2-322e0d7dd6b5.gif)

**Comment by Hazel6869** [comment] 2022-11-07 09:22
@guoqqqi can you assign this issue to me ？

**Comment by Baoyuantop** [comment] 2023-01-20 08:25
I can't reproduce this problem using the master branch code.

**Closed** 2023-02-27 08:20 UTC
Labels: bug, checking
