### ISSUE TITLE
request help: invalid secret type (must be string or function)

### ISSUE THREAD

**Issue by zlchanger** [apache/apisix-dashboard#663] opened 2020-11-02 08:25 UTC
### Issue description

I used the JWT plug-in for Apisix. The JWT configuration algorithm is HS512, base64_secret: true, and then key and secret are configured, but the call prompts invalid Secret Type (must be string or function), my secret is {^ h1k4&} 2? WN =. This one is a little bit more complicated, it has a lot of special symbols in it, and the last one is' = '. I tried to make secret a little bit simpler, like 1111, but this didn't happen. Why？

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS:

**Comment by zlchanger** [comment] 2020-11-02 10:46
> Look like dashboard's issue? Which version of dashboard you are using?

自带的吧，我参照你们的docker-example做的，1.2版本的apisix

**Comment by zlchanger** [comment] 2020-11-02 10:54
你们有最新版本的docker-example吗，我直接把版本从1.2改为2.0后，接口请求都变为403了

**Comment by juzhiyuan** [comment] 2020-11-02 12:16
Please use the dashboard 2.0 RC2 from the v2.0 branch, and it only supports deploying manually. Deploying with Docker is still under development according to this PR[1]

[1] https://github.com/apache/apisix-dashboard/pull/657#pullrequestreview-521510184

**Comment by juzhiyuan** [comment] 2020-11-02 12:21
> Look like dashboard's issue? Which version of dashboard you are using?

The dashboard you are using is 1.0, but I'm not sure if this error is returned from APISIX or Golang? Could you please have a try on the latest dashboard? This issue may be fixed, or I will have a try on the latest one in 1 week before RC3 releases.

**Comment by zlchanger** [comment] 2020-11-03 02:59
我打算先把apisix升级到2.0，现在很明显docker内部已经是2.0了，但为什么内部可以访问，外面却访问不了，端口我已经映射出来了，而且config.yaml里面的allow_admin也被我直接注释掉了
![avatar](https://apollobucket.oss-cn-beijing.aliyuncs.com/error.png)

**Comment by juzhiyuan** [comment] 2020-11-03 03:23
Let's cc @spacewander @Miss-you

**Comment by idbeta** [comment] 2020-11-03 03:36
> 我打算先把apisix升级到2.0，现在很明显docker内部已经是2.0了，但为什么内部可以访问，外面却访问不了，端口我已经映射出来了，而且config.yaml里面的allow_admin也被我直接注释掉了
@zlchanger You should raise a new issue in the APACHE APISIX project.

**Comment by zlchanger** [comment] 2020-11-03 03:37
> You should raise a new issue in the APACHE APISIX project.

OK

**Comment by zlchanger** [comment] 2020-11-03 06:52
> > Look like dashboard's issue? Which version of dashboard you are using?
> 
> The dashboard you are using is 1.0, but I'm not sure if this error is returned from APISIX or Golang? Could you please have a try on the latest dashboard? This issue may be fixed, or I will have a try on the latest one in 1 week before RC3 releases.

我已经把apisix升级到2.0，dashboard也是最新的2.0的，但配上这个jwt还是报错，我尝试将secret改的简单一点，没有特殊符号后，就OK了，但这个secret不是我这边负责的，所以我们的secret暂时没法变动

![avatar](https://apollobucket.oss-cn-beijing.aliyuncs.com/%E6%96%B0%E7%89%88.png)

**Comment by juzhiyuan** [comment] 2020-11-03 06:56
> 还是报错，

Let's check.

**Comment by idbeta** [comment] 2020-11-03 07:11
@zlchanger Can you provide the screenshot of the error report?

**Comment by idbeta** [comment] 2020-11-04 04:23
@zlchanger I used docker to install the APISIX dashboard 2.0 version and did not have this “ secret” problem, @nic-chen can you give some advice?

**Comment by juzhiyuan** [comment] 2020-11-04 04:32
Hi @zlchanger, our QA couldn't reproduce this issue, so I have to close this now.

If you could reproduce this & give more detailed steps, welcome to reopen this one, thanks for your report!

**Comment by spacewander** [comment] 2020-11-06 09:16
@zlchanger 
I guess I know why. You select the `base64_secret`, but your secret `{^h1k4&}2?WN=` is not in base64 format.

**Comment by juzhiyuan** [comment] 2020-11-06 09:22
@zlchanger kindly recheck this issue, if everything works as expectedly, please close this issue.

**Comment by juzhiyuan** [comment] 2020-11-10 07:45
Not sure if this issue gets resolved?

**Comment by spacewander** [comment] 2020-11-10 08:10
Consider solved.

**Closed by spacewander** 2020-11-10 08:10 UTC
Labels: backend, checking
