### ISSUE TITLE
Build docker image report "Error running install script for optional dependency"

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix-dashboard#989] opened 2020-12-08 10:57 UTC
# Bug report
When I use docker to build the image, the console output contains error messages
```
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "/usr/local/apisix-dashboard/web/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /usr/local/apisix-dashboard/web/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.1 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - \"python\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python2\" can be used
gyp ERR! find Python - \"python2\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python3\" can be used
gyp ERR! find Python - \"python3\" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 3.10.0-1062.12.1.el7.x86_64
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /usr/local/apisix-dashboard/web/node_modules/node-pty
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

Although this error message can be ignored, it seems that this error can be avoided as much as possible?

## System information

- OS: [e.g. macOS, Windows] `CentOS Linux release 7.9.2009 (Core)`
- Browser (if applies) [e.g. Chrome, Safari, Edge]
- Version: [e.g. 2.0-rc3] `v2.1.1`

**Comment by juzhiyuan** [comment] 2020-12-08 11:10
This error is due to node gyp, from frontend, just ignored this error.

**Comment by imjoey** [comment] 2020-12-30 09:07
@Caelebs @juzhiyuan , I can NOT reproduce this error. I'm able to successfully build the docker image with the latest code. In the meantime, your logs shows out that the root cause may be lack of valid Python installation. Could you please rerun `docker build` after install Python? Thanks.

**Comment by juzhiyuan** [comment] 2020-12-30 10:04
Thanks for your verification, I could see this error, but it's not urgent 😂 it won't effect the fe building.

**Comment by imjoey** [comment] 2020-12-30 10:37
> Thanks for your verification, I could see this error, but it's not urgent 😂 it won't effect the fe building.

@juzhiyuan that's kind of weird. Will investigate on it. Thanks.

**Comment by juzhiyuan** [comment] 2021-01-04 01:54
not urgent, close this.

**Closed by juzhiyuan** 2021-01-04 01:54 UTC
Labels: frontend, good first issue
