### ISSUE TITLE
WebUI loading all the time..

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix-dashboard#1905] opened 2021-05-20 02:56 UTC
## Issue description
When i click the service or route button, the webui always loading
![image](https://user-images.githubusercontent.com/52538259/118911399-b3383d00-b958-11eb-9c41-55524f6be33c.png)
then i checked the response from backend interfaces, All the backend interfaces responded successfully
![image](https://user-images.githubusercontent.com/52538259/118911553-f4305180-b958-11eb-8f89-83af6e82140b.png)
![image](https://user-images.githubusercontent.com/52538259/118911556-f5fa1500-b958-11eb-96f9-e04c077dbb46.png)
So i guess there may something wrong with dashboard

* apisix version (cmd: `apisix version`): 2.4
* dashboard: 2.5

**Comment by liuxiran** [comment] 2021-05-20 06:32
Hi @Marco-Zheng ,  I checked both the code published in 
* `https://archive.apache.org/dist/apisix/dashboard/2.5/` 
* `https://github.com/apache/apisix-dashboard/tree/v2.5`, 

I did not reproduce your issue in my local env.
Could you provide more detailed information about this issue？

1. where does the V2.5 dashboard source code come from? 
2. how do you launched the dashboard?
3. what is the version of your browser?
4. could you also help to check the `Console` tab of your dev-tool to see if there are any error logs

Thanks

**Comment by Marco-Zheng** [comment] 2021-05-21 02:41
> Hi @Marco-Zheng , I checked both the code published in
> 
> * `https://archive.apache.org/dist/apisix/dashboard/2.5/`
> * `https://github.com/apache/apisix-dashboard/tree/v2.5`,
> 
> I did not reproduce your issue in my local env.
> Could you provide more detailed information about this issue？
> 
> 1. where does the V2.5 dashboard source code come from?
> 2. how do you launched the dashboard?
> 3. what is the version of your browser?
> 4. could you also help to check the `Console` tab of your dev-tool to see if there are any error logs
> 
> Thanks

@liuxiran liu
we deploy V2.5 dashboard by helm chart on k8s cluster, the version of google is 83.0.4103.106
The problem is incidental, i have checked the console, no error founded, when i use `cmd+R` to refresh WebUI, it's worked well
![image](https://user-images.githubusercontent.com/52538259/119073947-bac31900-ba20-11eb-807a-5e970953b23c.png)

**Comment by juzhiyuan** [comment] 2021-05-22 02:34
> 83.0.4103.106

Couldn't reproduce, too. Would you mind having a date and have an online screen sharing next Monday (21:00)?

**Comment by coolbeevip** [comment] 2021-05-22 15:34
I occasionally have the same problem in the Chrome browser after restarting APISIX.

When I clear the browser cache or use Safari, it is OK

* apisix version:

```
$ ./bin/apisix version
/usr/local/Cellar/openresty/1.19.3.1_1/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.5
```

* OS: 

```shell
$ uname -a
Darwin bogon 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

* apisix-dashboard version:

```shell
$ ./manager-api
The manager-api is running successfully!

Version : 2.6
GitHash : 9728a43
Listen  : 0.0.0.0:9000
```

**Comment by juzhiyuan** [comment] 2021-05-23 07:45
> I occasionally have the same problem in the Chrome browser after restarting APISIX.
> 
> When I clear the browser cache or use Safari, it is OK
> 
> * apisix version:
> 
> ```
> $ ./bin/apisix version
> /usr/local/Cellar/openresty/1.19.3.1_1/luajit/bin/luajit ./apisix/cli/apisix.lua version
> 2.5
> ```
> 
> * OS:
> 
> ```shell
> $ uname -a
> Darwin bogon 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
> ```
> 
> * apisix-dashboard version:
> 
> ```shell
> $ ./manager-api
> The manager-api is running successfully!
> 
> Version : 2.6
> GitHash : 9728a43
> Listen  : 0.0.0.0:9000
> ```

@Marco-Zheng Hi, would you like to have a try?

**Comment by iamayushdas** [comment] 2021-05-23 08:06
We have many unoptimised images lying in this repo, which could be the main reason behind it

**Comment by Marco-Zheng** [comment] 2021-05-24 05:35
> > I occasionally have the same problem in the Chrome browser after restarting APISIX.
> > When I clear the browser cache or use Safari, it is OK
> > 
> > * apisix version:
> > 
> > ```
> > $ ./bin/apisix version
> > /usr/local/Cellar/openresty/1.19.3.1_1/luajit/bin/luajit ./apisix/cli/apisix.lua version
> > 2.5
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * OS:
> > 
> > ```shell
> > $ uname -a
> > Darwin bogon 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * apisix-dashboard version:
> > 
> > ```shell
> > $ ./manager-api
> > The manager-api is running successfully!
> > 
> > Version : 2.6
> > GitHash : 9728a43
> > Listen  : 0.0.0.0:9000
> > ```
> 
> @Marco-Zheng Hi, would you like to have a try?

@juzhiyuan Hi, i try to clear cache, it works, thanks a lot

**Comment by Marco-Zheng** [comment] 2021-05-24 05:37
> We have many unoptimised images lying in this repo, which could be the main reason behind it @Marco-Zheng

@iamayushdas Ok, thanks for your reply

**Comment by juzhiyuan** [comment] 2021-05-25 01:46
fine, it seems that this issue has been resolved. I will close it now :)

**Closed** 2021-05-25 01:46 UTC
Labels: bug, checking
